id: AA8A48456
base_file: fD873.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:43:36.628719
  last_modified_at: 2022-05-30 18:43:36.628729
