id: AA8A48456
base_file: fD1D5.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:43:36.626169
  last_modified_at: 2022-05-30 18:43:36.626193
