id: AA8A48456
base_file: f57E7.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:43:36.607254
  last_modified_at: 2022-05-30 18:43:36.607262
