id: AA8A48456
base_file: fAAE7.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:43:36.619700
  last_modified_at: 2022-05-30 18:43:36.619706
