id: AA8A48456
base_file: f85B2.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:43:36.615155
  last_modified_at: 2022-05-30 18:43:36.615192
